### Выполнил студент группы: БВТ2001 Халилов Назим Латифович

## Задача 1. «Треугольник с максимальным периметром»

Массив A состоит из целых положительных чисел длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно
составить треугольник с положительной площадью функция возвращает 0

In [8]:
import numpy

def matrixgenerate():
    n=int(input())
    massiv = numpy.random.randint(0, 20, size=(n))
    massiv = sorted(massiv, reverse=True)
    for i, j in enumerate(massiv):
        print("massiv[", i, "]=", j)
    return massiv

def perimetr(massiv):
    P=0
    
    for i in range(len(massiv)-2):
        if massiv[i] < massiv[i+1] + massiv[i+2]:
            return massiv[i]+massiv[i+1]+massiv[i+2]

massiv = matrixgenerate()
# leng=int(input())
# massiv=[0]*leng
# for i in range(len(massiv)):
#    massiv[i]=int(input())
# sorted(massiv)
# for i, j in enumerate(massiv):
#    print("massiv[", i, "]=", j)
P=perimetr(massiv)
print(P)

4
massiv[ 0 ]= 19
massiv[ 1 ]= 18
massiv[ 2 ]= 10
massiv[ 3 ]= 7
47


## Задача 2. «Максимальное число»

   Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

   **Замечание:** Результат может быть очень большим числом, поэтому представьте его как
string, а не integer.

In [12]:
def check(a,b):
    one=str(a) + str(b)
    two=str(b) + str(a)
    if int(one) > int(two):
        return True
    else:
        return False
    
def shell(massline):
    length = len(massline)
    l=length
    while l > 0:
        for i in range(length-l):
            j = i
            while j >= 0 and check(massline[j+l], massline[j]):
                massline[j], massline[j+l]=massline[j+l], massline[j]
                j = j - l
        l = int(l/2)
    strr = ""
    for i in range(len(massline)):
        strr = strr + "" + str(massline[i])
    return strr

mas1=[10,2]
mas2=[3,30,34,5,9]
mas3=[1]
mas4=[10]
mas5=[34323,3432]
print(shell(mas1))
print(shell(mas2))
print(shell(mas3))
print(shell(mas4))
print(shell(mas5))

210
9534330
1
10
343234323


## Задача 3. «Сортировка диагоналей в матрице»

Дана матрица mat размером m * n, значения целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу

In [9]:
import numpy

In [9]:
m, n= map(int, input('Введите m и n:').split(' '))
massiv = numpy.random.randint(0, 20, size=(m, n))
print(massiv)
for i in range(0,m):
    for j in range(0,n):
        l = j
        k = i
        while k < m and l < n:
            if massiv[i][j]>massiv[k][l]:
                print ("заменяет " , massiv[k][l] ," на " , massiv[i][j] )
                massiv[i][j], massiv[k][l]=massiv[k][l], massiv[i][j]
            k=k+1
            l=l+1
print("\n")
print(massiv)

Введите m и n:5 3
[[ 5 15  0]
 [ 5 18  3]
 [ 8  0  0]
 [ 3 16  7]
 [15  2  2]]
заменяет  0  на  5
заменяет  3  на  15
заменяет  0  на  5
заменяет  5  на  18
заменяет  2  на  8
заменяет  2  на  3
заменяет  8  на  16


[[ 0  3  0]
 [ 0  5 15]
 [ 2  5 18]
 [ 2  8  7]
 [15  3 16]]
